---
downloads: ~/.ansible-downloads/

dotfiles_repo: https://github.com/idolize/dotfiles-mac.git
dotfiles_repo_accept_hostkey: true
dotfiles_repo_local_destination: ~/Dev/dotfiles-mac

homebrew_installed_packages:
  - ansible
  - fish
  - git
  - gh
  - gpg
  - mcrypt
  - nmap
  - nvm
  - python
  - ssh-copy-id
  - readline
  - openssl
  - wget

homebrew_taps:
  - homebrew/core

osx_script: "~/.osx --no-restart"

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: []
# - name: drush
#   state: present # present/absent, default: present
#   version: "^8.1" # default: N/A
gem_packages: []
# - name: bundler
#   state: present # present/absent/latest, default: present
#   version: "~> 1.15.1" # default: N/A
npm_packages:
  - name: npm-check-updates
    state: latest # present/absent/latest, default: present
#   version: "^2.6" # default: N/A
pip_packages: []
# - name: mkdocs
#   state: present # present/absent/latest, default: present
#   version: "0.16.3" # default: N/A

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []
